"""user add tokens

Revision ID: 854d4ce9a98c
Revises: cf86b1d435a2
Create Date: 2019-07-11 10:38:38.230338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854d4ce9a98c'
down_revision = 'cf86b1d435a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
